### ISSUE TITLE
Unintuitive

### ISSUE THREAD

**Issue by masterofobzene** [BenPyton/NodalSoundEditor#4]
You have to take a course to understand how to make a tone repeat, simply not worth the time. It would be usable if basic stuff like repeating the generated wave were easily triggered from a menu instead of a graphical programming interface 😞

**Comment by hartwork** [comment]
@BenPyton my vote for closing this ticket as out-of-place and not constructive for a software marked as alpha officially that is free to be used or not be used. I think it's great that you're sharing this software with the world as software libre despite alpha state.

**Comment by BenPyton** [comment]
@hartwork Yes you'r right, it is not very constructive, but asks a somewhat legit question: why do place the repeat as a node in the graphical interface instead of a simple setting in a menu?

Just for posterity, I will answer this question.

It is not just a way to repeat the entire resulting sound.
Using a node for repeat feature allow the users to do much more complex behaviour than a simple repeat. For example, we can repeat some parts of the sound and combine them in a non repeated sound.

Also, about the "unintuitive" feeling of the software, I will reply it is much much MUCH more simple and intuitive to understand than real synthetizers or their simulators like [VCV Rack 2](https://vcvrack.com/Rack).
(And it is not meant to be a synth simulator, just a sound generator)
